version: '2'
services:
 am-analytics:
  networks:
   api_manager_net:
    ipv4_address: 172.25.0.101
  image : nuwanpallewela/wso2am_analytics_2.0.0:v1.0.0
  environment:
   SLEEP: 5
 api-manager:
  networks:
   api_manager_net:
    ipv4_address: 172.25.0.102
  image : nuwanpallewela/wso2am_2.0.0:v1.0.0
  depends_on:
   - "am-analytics"
  links:
   - am-analytics
  environment:
   SLEEP: 90
   ANALYTICS: "true"
  ports:
   - "80:9763"
   - "443:9443"
   - "8280:8280"
   - "8243:8243"
networks:
 api_manager_net:
  driver: bridge
  ipam:
   config:
    -subnet: 172.25.0.0/24
